# Generated by Django 3.2.5 on 2021-07-13 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movies_app.actor'),
        ),
    ]
