# Generated by Django 3.2.5 on 2021-08-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0009_alter_star_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_admin',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='movies/video-camera.png', upload_to='movies/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
